routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::resource('/products', 'ProductController');
Route::get('products/delete/{id}', 'ProductController@destroy')->name('products.delete');
Route::resource('/sales', 'SaleController');
Route::get('sales/delete/{id}', 'SaleController@destroy')->name('sales.delete');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',
        'img',
        'stock',
        'base_price',
        'factory_price',
        'price_with_tax',
        'fee_gain',
    ];
}

app/Models/Sale.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sale extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'product_id',
        'sale_date',
        'quantity',
        'sub_total',
        'total',
        'sale_type',
        'email',
        'cellphone',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function adminlte_image(){
        return 'https://picsum.photos/300/300';
    }

    public function adminlte_desc(){
        return 'Admisnistrador';
    }

    public function adminlte_profile_url(){
        return 'profile/username';
    }


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models;

use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::latest()->paginate(5);
  
        return view('product.list',compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 7);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'stock' => 'required',
            'factory_price' => 'required',
            'price_with_tax' => 'required',
        ]);
  
        Product::create($request->all());
   
        return redirect()->route('products.index')
                        ->with('success',':) Producto creado.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {   
        return view('product.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->except('_method','_token','submit');
        $request->validate([
            'name' => 'required',
            'stock' => 'required',
            'factory_price' => 'required',
            'price_with_tax' => 'required',
        ]);
  
        $post = Product::find($id);

        $post->update($data);
        
        return redirect()->route('products.index')
        ->with('success','Product deleted successfully');
         
   
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $post = Product::find($id);
        $post->delete();
  
        return redirect()->route('products.index')
                        ->with('success','Product deleted successfully');
    }
}

app/Http/Controllers/SaleController.php
<?php

namespace App\Http\Controllers;
use App\Models\Sale;
use Illuminate\Http\Request;

class SaleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sales = Sale::latest()->paginate(5);
  
        return view('sales.list',compact('sales'))
            ->with('i', (request()->input('page', 1) - 1) * 7);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('adminlte::page')

@section('title','DashBoard')

@section('content_header')
    <h1>Pasaje Cervecero</h1>
@stop


@section('content')
    <p>Wellcome to this beatiful</p>
@stop


@section('css')
    <link rel='stylesheet' href='/css/admin_custom.css'>
@stop

@section('js')
    <script type='text/javascript' src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        Swal.fire(
            'Good job!',
            'You clicked the button!',
            'success'
            )
    </script>
@stop

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/product/create.blade.php
@extends('adminlte::page')

@section('content')

<div class="row">
        <div class="col-lg-10">
            <h2>Agregar nuevo producto</h2>
        </div>
        <div class="col-lg-2">
            <a class="btn btn-warning" href="{{ route('products.index') }}"> Regresar</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>:(</strong> Existe un error.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('products.store') }}" method="POST">
    @csrf
  
        <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="form-group">
                        <strong>Nombre:</strong>
                        <input type="text" name="name" class="form-control" placeholder="Nombre">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="form-group">
                        <strong>Stock:</strong>
                        <input type="text" name="stock" class="form-control" placeholder="Stock">
                    </div>
                </div>
        </div>
    
        <div class="col-lg-10">
            <h3>Precios</h3>
        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-3 col-md-3">
                <div class="form-group">
                    <strong>Fabrica:</strong>
                    <input type="number" step="0.01" id="factory_price"  name="factory_price" class="form-control" placeholder="0.00">
                </div>
            </div>
            <div class="col">
                <strong>Publico:</strong>
                <input type="number" step="0.01" id="price_with_tax" name="price_with_tax" class="form-control" placeholder="0.00">
            </div>

            <div class="col-xs-12 col-sm-3 col-md-3">
                <div class="form-group">
                    <strong>Sin IVA:</strong>
                    <input type="number" id="base_price" step="0.01" name="base_price" class="form-control" placeholder="0.00">
                </div>
            </div>

            <div class="col-xs-12 col-sm-3 col-md-3">
                <div class="form-group">
                    <strong>Ganancia:</strong>
                    <input type="number" step="0.01" id="fee_gain" name="fee_gain" class="form-control" placeholder="0.00">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-success">GUARDAR</button>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

@section('js')
    <script type='text/javascript'>
        $("#price_with_tax").focusout(function() {
            $price_with_tax = $("#price_with_tax").val();
            $valor = $price_with_tax - ($price_with_tax*0.12)
            $('#base_price').val($valor.toFixed(2));

            $factory_price = $("#factory_price").val();

            $fee_gain =  $price_with_tax - $factory_price;
            $('#fee_gain').val($fee_gain.toFixed(2));
        });
    </script>
@endsection

resources/views/product/edit.blade.php
@extends('adminlte::page')

@section('content')

<div class="row">
        <div class="col-lg-10">
            <h2>Agregar nuevo producto</h2>
        </div>
        <div class="col-lg-2">
            <a class="btn btn-warning" href="{{ route('products.index') }}"> Regresar</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>:(</strong> Existe un error.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('products.update',$product->id) }}" method="POST">
    @csrf
    @method('PUT')
        <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="form-group">
                        <strong>Nombre:</strong>
                        <input type="text" name="name" value="{{ $product->name }}" class="form-control" placeholder="Nombre">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="form-group">
                        <strong>Stock:</strong>
                        <input type="text" name="stock" value="{{ $product->stock }}" class="form-control" placeholder="Stock">
                    </div>
                </div>
        </div>
    
        <div class="col-lg-10">
            <h3>Precios</h3>
        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-3 col-md-3">
                <div class="form-group">
                    <strong>Fabrica:</strong>
                    <input type="number" step="0.01" value="{{ $product->factory_price }}" id="factory_price"  name="factory_price" class="form-control" placeholder="0.00">
                </div>
            </div>
            <div class="col">
                <strong>Publico:</strong>
                <input type="number" step="0.01" value="{{ $product->price_with_tax }}" id="price_with_tax" name="price_with_tax" class="form-control" placeholder="0.00">
            </div>

            <div class="col-xs-12 col-sm-3 col-md-3">
                <div class="form-group">
                    <strong>Sin IVA:</strong>
                    <input type="number" step="0.01" value="{{ $product->base_price }}" id="base_price" name="base_price" class="form-control" placeholder="0.00">
                </div>
            </div>

            <div class="col-xs-12 col-sm-3 col-md-3">
                <div class="form-group">
                    <strong>Ganancia:</strong>
                    <input type="number" step="0.01" value="{{ $product->fee_gain }}"  id="fee_gain" name="fee_gain" class="form-control" placeholder="0.00">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-success">GUARDAR</button>
                </div>
            </div>
        </div>
    </div>
   
</form>
@endsection

@section('js')
    <script type='text/javascript'>
        $("#price_with_tax").focusout(function() {
            $price_with_tax = $("#price_with_tax").val();
            $valor = $price_with_tax - ($price_with_tax*0.12)
            $('#base_price').val($valor.toFixed(2));

            $factory_price = $("#factory_price").val();

            $fee_gain =  $price_with_tax - $factory_price;
            $('#fee_gain').val($fee_gain.toFixed(2));
        });
    </script>
@endsection

resources/views/product/list.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        <div class="col-lg-10">
                <h2>Catalogo de Productos</h2>
        </div>
        <div class="col-lg-2">
            <a class="btn btn-success" href="{{ route('products.create') }}">Añadir Nuevo</a>
        </div>
    </div>
 
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
 
    <table class="table table-dark">
        <tr>
            <th>No</th>
            <th>Nombre</th>
            <th>Stock</th>
            <th>Ganancia</th>
            <th width="280px">Action</th>
        </tr>
        @php
            $i = 0;
        @endphp
        @foreach ($products as $product)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->stock }}</td>
                <td>{{ $product->fee_gain }}</td>
                <td>
                    <form action="{{ route('products.index',$product->id) }}" method="POST">
                        <!-- <a class="btn btn-info" href="{{ route('products.index',$product->id) }}">Show</a> -->
                        <a class="btn btn-primary" href="{{ route('products.edit',$product->id) }}">Editar</a>
                        <a class="btn btn-danger" href="{{ route('products.delete',$product->id) }}">Eliminar</a>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
@endsection

resources/views/sales/list.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        <div class="col-lg-10">
                <h2>Ventas del dia</h2>
        </div>
        <div class="col-lg-2">
            <a class="btn btn-success" href="{{ route('products.create') }}">Ingresar venta</a>
        </div>
    </div>
 
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
 
    <table class="table table-dark">
        <tr>
            <th>No</th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Fecha</th>
            <th>Total</th>
            <th>Tipo</th>
            <th width="280px">Action</th>
        </tr>
        @php
            $i = 0;
        @endphp
        @foreach ($sales as $sale)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $sale->product_id }}</td>
                <td>{{ $sale->quantity }}</td>
                <td>{{ $sale->sale_date }}</td>
                <td>{{ $sale->total }}</td>
                <td>{{ $sale->sale_type }}</td>
                <td>
                    <form action="{{ route('sales.index',$sale->id) }}" method="POST">
                        <!-- <a class="btn btn-info" href="{{ route('sales.index',$sale->id) }}">Show</a> -->
                        <a class="btn btn-primary" href="{{ route('sales.edit',$sale->id) }}">Editar</a>
                        <a class="btn btn-danger" href="{{ route('sales.delete',$sale->id) }}">Eliminar</a>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
@endsection